# Generated by Django 3.0.6 on 2020-05-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя продукта (Ремешок для)')),
                ('image_on_home', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фото на главной странице')),
                ('description', models.CharField(blank=True, max_length=600, verbose_name='Описание продукта')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена')),
            ],
        ),
    ]
